#
# (C) Copyright 2014
# Avionic Design GmbH <www.avionic-design.de>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= ../../nvidia/venice2/as3722_init.o
obj-y	+= meerkat.o

# Taken from nvidia common
obj-y	+= ../../nvidia/common/board.o
obj-$(CONFIG_TEGRA_CLOCK_SCALING) += ../../nvidia/common/emc.o
